// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoPraticoCodenation.Models;

namespace ProjetoPraticoCodenation.Migrations
{
    [DbContext(typeof(ProjetoPraticoContext))]
    partial class ProjetoPraticoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoPraticoCodenation.Models.LogErro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_log")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasColumnName("ds_ambiente")
                        .HasMaxLength(50);

                    b.Property<bool>("Arquivado")
                        .HasColumnName("fl_arquivado");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnName("dt_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("ds_log")
                        .HasMaxLength(8000);

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasColumnName("cd_evento")
                        .HasMaxLength(50);

                    b.Property<string>("IPOrigem")
                        .IsRequired()
                        .HasColumnName("nr_ip_origem")
                        .HasMaxLength(50);

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnName("cd_nivel")
                        .HasMaxLength(50);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnName("ds_titulo_log")
                        .HasMaxLength(250);

                    b.Property<int?>("UsuarioId");

                    b.Property<string>("UsuarioOrigem")
                        .IsRequired()
                        .HasColumnName("nm_usuario_origem")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("log_erros");
                });

            modelBuilder.Entity("ProjetoPraticoCodenation.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_usuario")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnName("nm_login")
                        .HasMaxLength(30);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nm_usuario")
                        .HasMaxLength(100);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("ds_senha")
                        .HasMaxLength(255);

                    b.Property<string>("Token")
                        .HasColumnName("cd_token")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ProjetoPraticoCodenation.Models.LogErro", b =>
                {
                    b.HasOne("ProjetoPraticoCodenation.Models.Usuario")
                        .WithMany("Logs")
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
