FROM microsoft/dotnet:2.2-sdk
WORKDIR /app
EXPOSE 80

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

ENTRYPOINT ["dotnet", "run", "--urls", "http://*:5000;http://*:5001"]
